-- Execute este script no SQL Editor do seu projeto Supabase

-- Criar tabela de Despesas
CREATE TABLE public.expenses (
    id bigint generated by default as identity primary key,
    description text not null,
    company text,
    amount numeric(10, 2) not null,
    paid_amount numeric(10, 2) default 0,
    due_date date not null,
    type text not null,
    status text not null check (status in ('pending', 'paid')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Caso a tabela já exista, execute para adicionar as novas colunas:
-- ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS company text;
-- ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS paid_amount numeric(10, 2) DEFAULT 0;

-- Criar tabela de Receitas
CREATE TABLE public.incomes (
    id bigint generated by default as identity primary key,
    source text not null,
    amount numeric(10, 2) not null,
    date text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar tabela de Tipos de Despesa (Categorias)
CREATE TABLE public.expense_types (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inserir tipos padrão
INSERT INTO public.expense_types (name) VALUES 
('Moradia'), ('Alimentação'), ('Transporte'), ('Saúde'), 
('Educação'), ('Lazer'), ('Serviços'), ('Outros')
ON CONFLICT (name) DO NOTHING;

-- Criar tabela de Empresas / Fornecedores
CREATE TABLE public.companies (
    id bigint generated by default as identity primary key,
    name text not null unique,
    default_type text not null default 'Outros',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inserir empresas de exemplo
INSERT INTO public.companies (name, default_type) VALUES
('Copel / Energia', 'Moradia'),
('Sanepar / Água', 'Moradia'),
('Internet / Fibra', 'Serviços'),
('Supermercado', 'Alimentação'),
('Netflix', 'Lazer'),
('Spotify', 'Lazer'),
('Posto de Combustível', 'Transporte'),
('Farmácia', 'Saúde')
ON CONFLICT (name) DO NOTHING;

-- Ativar segurança em nível de linha (RLS) para permitir acesso anônimo inicial
-- NOTA: Em produção, você deve usar RLS atrelado à autenticação de usuário!
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous select expenses" ON public.expenses FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert expenses" ON public.expenses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update expenses" ON public.expenses FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete expenses" ON public.expenses FOR DELETE USING (true);

CREATE POLICY "Allow anonymous select incomes" ON public.incomes FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert incomes" ON public.incomes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update incomes" ON public.incomes FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete incomes" ON public.incomes FOR DELETE USING (true);

CREATE POLICY "Allow anonymous select expense_types" ON public.expense_types FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert expense_types" ON public.expense_types FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update expense_types" ON public.expense_types FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete expense_types" ON public.expense_types FOR DELETE USING (true);

CREATE POLICY "Allow anonymous select companies" ON public.companies FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert companies" ON public.companies FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update companies" ON public.companies FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete companies" ON public.companies FOR DELETE USING (true);

-- Ativar o Realtime para as tabelas
alter publication supabase_realtime add table public.expenses;
alter publication supabase_realtime add table public.incomes;
alter publication supabase_realtime add table public.expense_types;
alter publication supabase_realtime add table public.companies;
