-- ==============================================================================
-- FINANTE: SCRIPT COMPLETO E SEGURO (CRIAÇÃO DE TABELAS + RLS + SUPABASE AUTH)
-- Execute este script no SQL Editor do seu projeto Supabase
-- ==============================================================================

-- 1. CRIAR AS TABELAS CASO NÃO EXISTAM (COM user_id VINCULADO AO AUTH)
CREATE TABLE IF NOT EXISTS public.expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    description text NOT NULL,
    company text,
    amount numeric(10, 2) NOT NULL,
    paid_amount numeric(10, 2) DEFAULT 0,
    due_date date NOT NULL,
    paid_date date,
    payment_method text,
    notes text,
    excess_type text,
    bill_attachment text,
    bill_name text,
    receipt_attachment text,
    receipt_name text,
    type text NOT NULL DEFAULT 'Outros',
    status text NOT NULL CHECK (status IN ('pending', 'paid')) DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.incomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    source text NOT NULL,
    amount numeric(10, 2) NOT NULL,
    date text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.expense_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    name text NOT NULL,
    default_type text NOT NULL DEFAULT 'Outros',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.investments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    asset text NOT NULL,
    category text NOT NULL DEFAULT 'Renda Fixa',
    amount numeric(10, 2) NOT NULL,
    date text NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. GARANTIR QUE TODAS AS COLUNAS EXISTAM (CASO AS TABELAS JÁ EXISTISSEM)
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS paid_amount numeric(10, 2) DEFAULT 0;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS paid_date date;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS excess_type text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS bill_attachment text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS bill_name text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS receipt_attachment text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS receipt_name text;

ALTER TABLE public.incomes ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
ALTER TABLE public.expense_types ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();
ALTER TABLE public.investments ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();

-- 3. INSERIR DADOS PADRÃO (CATEGORIAS E EMPRESAS GLOBAIS COM user_id = NULL)
INSERT INTO public.expense_types (name, user_id) VALUES 
('Moradia', NULL), ('Alimentação', NULL), ('Transporte', NULL), ('Saúde', NULL), 
('Educação', NULL), ('Lazer', NULL), ('Serviços', NULL), ('Outros', NULL)
ON CONFLICT DO NOTHING;

INSERT INTO public.companies (name, default_type, user_id) VALUES
('Copel / Energia', 'Moradia', NULL),
('Sanepar / Água', 'Moradia', NULL),
('Internet / Fibra', 'Serviços', NULL),
('Supermercado', 'Alimentação', NULL),
('Netflix', 'Lazer', NULL),
('Spotify', 'Lazer', NULL),
('Posto de Combustível', 'Transporte', NULL),
('Farmácia', 'Saúde', NULL)
ON CONFLICT DO NOTHING;

-- 4. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;

-- 5. REMOVER POLÍTICAS ANTIGAS (SE EXISTIREM)
DROP POLICY IF EXISTS "Allow anonymous select expenses" ON public.expenses;
DROP POLICY IF EXISTS "Allow anonymous insert expenses" ON public.expenses;
DROP POLICY IF EXISTS "Allow anonymous update expenses" ON public.expenses;
DROP POLICY IF EXISTS "Allow anonymous delete expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can manage their own expenses" ON public.expenses;

DROP POLICY IF EXISTS "Allow anonymous select incomes" ON public.incomes;
DROP POLICY IF EXISTS "Allow anonymous insert incomes" ON public.incomes;
DROP POLICY IF EXISTS "Allow anonymous update incomes" ON public.incomes;
DROP POLICY IF EXISTS "Allow anonymous delete incomes" ON public.incomes;
DROP POLICY IF EXISTS "Users can manage their own incomes" ON public.incomes;

DROP POLICY IF EXISTS "Allow anonymous select expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Allow anonymous insert expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Allow anonymous update expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Allow anonymous delete expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Users can view default and own expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Users can insert own expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Users can update own expense_types" ON public.expense_types;
DROP POLICY IF EXISTS "Users can delete own expense_types" ON public.expense_types;

DROP POLICY IF EXISTS "Allow anonymous select companies" ON public.companies;
DROP POLICY IF EXISTS "Allow anonymous insert companies" ON public.companies;
DROP POLICY IF EXISTS "Allow anonymous update companies" ON public.companies;
DROP POLICY IF EXISTS "Allow anonymous delete companies" ON public.companies;
DROP POLICY IF EXISTS "Users can view default and own companies" ON public.companies;
DROP POLICY IF EXISTS "Users can insert own companies" ON public.companies;
DROP POLICY IF EXISTS "Users can update own companies" ON public.companies;
DROP POLICY IF EXISTS "Users can delete own companies" ON public.companies;

DROP POLICY IF EXISTS "Allow anonymous select investments" ON public.investments;
DROP POLICY IF EXISTS "Allow anonymous insert investments" ON public.investments;
DROP POLICY IF EXISTS "Allow anonymous update investments" ON public.investments;
DROP POLICY IF EXISTS "Allow anonymous delete investments" ON public.investments;
DROP POLICY IF EXISTS "Users can manage their own investments" ON public.investments;

-- 6. CRIAR POLÍTICAS SEGURAS (RLS)

-- Despesas: Cada usuário só gerencia as suas próprias
CREATE POLICY "Users can manage their own expenses" 
ON public.expenses 
FOR ALL 
TO authenticated 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- Receitas: Cada usuário só gerencia as suas próprias
CREATE POLICY "Users can manage their own incomes" 
ON public.incomes 
FOR ALL 
TO authenticated 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- Investimentos: Cada usuário só gerencia os seus próprios
CREATE POLICY "Users can manage their own investments" 
ON public.investments 
FOR ALL 
TO authenticated 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- Empresas / Fornecedores: Enxerga as globais (user_id IS NULL) e gerencia as suas
CREATE POLICY "Users can view default and own companies" 
ON public.companies 
FOR SELECT 
TO authenticated 
USING (user_id IS NULL OR auth.uid() = user_id);

CREATE POLICY "Users can insert own companies" 
ON public.companies 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own companies" 
ON public.companies 
FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own companies" 
ON public.companies 
FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- Categorias: Enxerga as globais (user_id IS NULL) e gerencia as suas
CREATE POLICY "Users can view default and own expense_types" 
ON public.expense_types 
FOR SELECT 
TO authenticated 
USING (user_id IS NULL OR auth.uid() = user_id);

CREATE POLICY "Users can insert own expense_types" 
ON public.expense_types 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own expense_types" 
ON public.expense_types 
FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own expense_types" 
ON public.expense_types 
FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- 7. ATIVAR O REALTIME
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.expenses;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.incomes;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.companies;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.expense_types;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.investments;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END $$;
