-- Execute este script no SQL Editor do seu projeto Supabase

-- Criar tabela de Despesas
CREATE TABLE public.expenses (
    id bigint generated by default as identity primary key,
    description text not null,
    amount numeric(10, 2) not null,
    due_date date not null,
    type text not null,
    status text not null check (status in ('pending', 'paid')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar tabela de Receitas
CREATE TABLE public.incomes (
    id bigint generated by default as identity primary key,
    source text not null,
    amount numeric(10, 2) not null,
    date text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ativar segurança em nível de linha (RLS) para permitir acesso anônimo inicial
-- NOTA: Em produção, você deve usar RLS atrelado à autenticação de usuário!
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous select expenses" ON public.expenses FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert expenses" ON public.expenses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update expenses" ON public.expenses FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete expenses" ON public.expenses FOR DELETE USING (true);

CREATE POLICY "Allow anonymous select incomes" ON public.incomes FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert incomes" ON public.incomes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update incomes" ON public.incomes FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete incomes" ON public.incomes FOR DELETE USING (true);

-- Ativar o Realtime para as tabelas
alter publication supabase_realtime add table public.expenses;
alter publication supabase_realtime add table public.incomes;
